### PR TITLE
add google analytics, and more fixes

### PR DESCRIPTION
**Pull request by vincerubinetti**
- add google analytics
- fix github actions; change `json` output to `yml` output
- add text to readme to help people editing the site in the future
- add note in `research-input.yml` about citation caching behavior
- update tybalt's paper

### CODE REVIEW

**Comment by vincerubinetti** [comment]
@cgreene @dongbohu Looks like that `EndBug/add-and-commit` gh-actions plugin is having problems:

```
Creating commit...
  [analytics 2b7ebd5] update Manubot-generated citations on research page
   1 file changed, 6 insertions(+), 6 deletions(-)
  Tagging commit...
  Pushing commits to repo...
  remote: Permission to greenelab/greenelab.com.git denied to github-actions[bot].
  fatal: unable to access 'https://github.com/greenelab/greenelab.com/': The requested URL returned error: 403
  Pushing tags to repo...
  remote: Permission to greenelab/greenelab.com.git denied to github-actions[bot].
  fatal: unable to access 'https://github.com/greenelab/greenelab.com/': The requested URL returned error: 403
```

**Comment by vincerubinetti** [comment]
Also worth mentioning that the github actions didn't even run until i had resolved the merge conflicts.

**Comment by cgreene** [comment]
Hmmm... I wonder if this has been an issue for some time - see https://github.com/EndBug/add-and-commit/issues/53

**Comment by vincerubinetti** [comment]
Going to try fixing it to `v4.0.0`

**Comment by cgreene** [comment]
I think that what's happening here is that it's failing to commit because of permissions with this being run against your fork. It's not displaying a failure message because of that ticket. If you merge this and then we run it in a branch, I expect it will work. Should we give that a shot?

**Pull request merged**
