### PR TITLE
Add new pub

### PR DESCRIPTION
**Pull request by ajlee21**

### CODE REVIEW

**Comment by ajlee21** [comment]
@vincerubinetti not sure if you can help with this error check. There is an error with the auto-cite generation

```
  Source 1 of 139 - doi.org/10.48550/arXiv.2203.13946
    Using Manubot to generate new citation
    Manubot could not generate citation
```

**Comment by ajlee21** [comment]
I'm not sure if this is related. But I also tried to update **existing** entries in the `sources.yml` file but got the following error

```
Run stefanzweifel/git-auto-commit-action@v4
Started: bash /home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/entrypoint.sh
INPUT_REPOSITORY value: .
INPUT_STATUS_OPTIONS: 
INPUT_BRANCH value: add_pub_take2
From https://github.com/greenelab/greenelab.com
 * [new branch]      add-disco2021           -> origin/add-disco2021
 * [new branch]      cgreene-preprint-to-pub -> origin/cgreene-preprint-to-pub
 * [new branch]      cgreene-two-pubs        -> origin/cgreene-two-pubs
 * [new branch]      main                    -> origin/main
fatal: invalid reference: add_pub_take2
Error: Invalid status code: 128
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1022:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5) {
  code: 128
}
Error: Invalid status code: 128
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1022:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
```
Which made me think that I couldn't update existing entries in the `sources.yml` file only add new entries. So I deleted the updates in commit [a2d6b9a](https://github.com/greenelab/greenelab.com/pull/45/commits/a2d6b9a82b2176fcf88de5a27517f9b08f73d6ef) but when I added a new entry I got the error described above

I read this [old issue](https://github.com/greenelab/lab-website-template/issues/96#issuecomment-908411841) where you mentioned that it might be an issue with permissions from my fork. But I did check that my forked repo has permissions.

**Comment by vincerubinetti** [comment]
> doi.org/10.48550/arXiv.2203.13946

I don't believe this is a [valid manubot identifier](https://github.com/greenelab/lab-website-template/wiki/Citations#sourcesyaml). I think you want `arxiv:2203.13946`.  Or if you really wanted to cite it with the url, `url:https://doi.org/10.48550/arXiv.2203.13946`. I'm pretty sure that is why Manubot cannot generate the citation for that one. The only other possibility is that the paper is too new and metadata for it isn't available yet.

Regarding the github actions problem, that should be a separate issue. Just to verify, when you created your fork, you enabled `Allow all actions and reusable workflows` and `Read and write permissions`, before opening this PR? 

If so, this seems to be an ongoing problem with `stefanzweifel/git-auto-commit-action`. I might have to start telling people that they just have to do PRs from a branch, not a fork. It seems like what's happening is that the target repo (in this case, `greenelab/greenelab.com`) is trying to run a workflow which makes a commit on a completely different repo (`ajlee21/greenelab.com#add_pub_take2`), and can either not find it, or doesn't have permissions to commit (write) to it.

**Comment by ajlee21** [comment]
>  doi.org/10.48550/arXiv.2203.13946
> 
> I don't believe this is a [valid manubot identifier](https://github.com/greenelab/lab-website-template/wiki/Citations#sourcesyaml). I think you want `arxiv:2203.13946`. Or if you really wanted to cite it with the url, `url:https://doi.org/10.48550/arXiv.2203.13946`. I'm pretty sure that is why Manubot cannot generate the citation for that one. The only other possibility is that the paper is too new and metadata for it isn't available yet.

Just tried to use the arxiv id and now there is the same `stefanzweifel/git-auto-commit-action@v4` error so some progress!

> Regarding the github actions problem, that should be a separate issue. Just to verify, when you created your fork, you enabled `Allow all actions and reusable workflows` and `Read and write permissions`, before opening this PR?

Yes

> If so, this seems to be an ongoing problem with `stefanzweifel/git-auto-commit-action`. I might have to start telling people that they just have to do PRs from a branch, not a fork. It seems like what's happening is that the target repo (in this case, `greenelab/greenelab.com`) is trying to run a workflow which makes a commit on a completely different repo (`ajlee21/greenelab.com#add_pub_take2`), and can either not find it, or doesn't have permissions to commit (write) to it.

I can open an issue for this

**Comment by vincerubinetti** [comment]
I'm going to open an issue on lab website template for that. For now, unfortunately, you'll probably have to redo this change yet again, except on a direct branch of  `greenelab.com` repo. Or if you don't feel like doing that, you could [build and commit the citations locally](https://github.com/greenelab/lab-website-template/wiki/Advanced-Editing#build-citations-locally), assuming you have conda and manubot installed.

**Comment by ajlee21** [comment]
Thanks so much @vincerubinetti for all your help! I'll make a new branch

**Pull request closed without merging**
