### PR TITLE
Update PhenomeXcan paper

### PR DESCRIPTION
**Pull request by miltondp**
Update PhenomeXcan paper, which was recently published. @cgreene

### CODE REVIEW

**Comment by vincerubinetti** [comment]
You'll need to build the output file for this change to have an effect:

https://github.com/greenelab/greenelab.com#making-changes-to-the-site

**Comment by cgreene** [comment]
@miltondp in the future if you work on a branch instead of a fork, github actions will automatically rebuild for you.

**Comment by miltondp** [comment]
@vincerubinetti , I ran the `./build.sh` script to update `_data/research-output.yml` before pushing, and the preview looks good. Not sure what I'm missing.

**Comment by vincerubinetti** [comment]
Oh i'm sorry I didn't see. Yes as long as `research-output.yml` got updated, this is fine.

**Pull request merged**
