### PR TITLE
Add COVID-19 review paper to research page

### PR DESCRIPTION
**Pull request by rando2**
I believe .yml falls under @cgreene 's purview based on the description!

### CODE REVIEW

**Comment by rando2** [comment]
Oops, I missed that there is a special Manubot tag! Updating now.

**Comment by vincerubinetti** [comment]
You'll need to build the output file for this change to have an effect:

https://github.com/greenelab/greenelab.com#making-changes-to-the-site

**Comment by cgreene** [comment]
Same as #49 - next time if you work on a branch it'll update automagically :)

Maybe we can merge these and then file a PR on a branch that updates one more paper to get an easy rebuild

**Comment by rando2** [comment]
Not sure if I should have, but I ran it here as well!

**Comment by rando2** [comment]
Thank you to @miltondp for volunteering as tribute to the merge conflict

**Pull request merged**
