### PR TITLE
Add miQC paper

### PR DESCRIPTION
**Pull request by arielah**

### CODE REVIEW

**Comment by arielah** [comment]
@vincerubinetti can I get some help understanding the deploy preview failure report?

**Comment by vincerubinetti** [comment]
I think this is happening because of this line:

```yaml
title: miQC: An adaptive probabilistic framework for quality control of single-cell RNA-sequencing data
```

The extra colon is confusing the yaml parser. You could surround it with double quotes to fix it, however the github actions will run and replace it anyway. I need to make a fix to the script to always quote the right hand side value. Bear with me, I'll get you some changes to the build script to put in this PR and hopefully fix it.

**Comment by cgreene** [comment]
Good 👀 !

**Comment by vincerubinetti** [comment]
@arielah it seems like you built this locally on your machine. To verify I've identified the problem correctly, could you double quote that `title` field in the `research-output` file, and run `start.sh` and see if it compiles correctly

**Comment by vincerubinetti** [comment]
It seems like the YAML parser was smart enough to quote things with a colon in them in the past, like for this paper:

```yaml
- title: 'SARS-CoV-2 and COVID-19: An Evolving Review of Diagnostics and Therapeutics'
```

So why isn't it doing it for this paper...

**Comment by arielah** [comment]
Is it because it's not in quotes like the covid paper is?

**Comment by cgreene** [comment]
The GitHub actions bot is getting permission denied. I wonder if @arielah made the change if it'd successfully commit the new output file.

**Comment by arielah** [comment]
Coming clean time: I didn't build this locally on my machine. I looked at the "files changed" tab from PR #31, copied it exactly, and then committed it. Sorry I broke everything.

**Comment by arielah** [comment]
> The GitHub actions bot is getting permission denied. I wonder if @arielah made the change if it'd successfully commit the new output file.

What change should I make, @cgreene?

**Comment by vincerubinetti** [comment]
> The GitHub actions bot is getting permission denied. I wonder if @arielah made the change if it'd successfully commit the new output file.

@arielah did you [enable github actions on your fork BEFORE making the PR](https://github.com/greenelab/lab-website-template/wiki/Basic-Editing#on-github)? That is required for the bot to work correctly. (I'm working on improving the instructions).

**Comment by vincerubinetti** [comment]
> Coming clean time: I didn't build this locally on my machine. I looked at the "files changed" tab from PR #31, copied it exactly, and then committed it. Sorry I broke everything.

Okay that makes sense. I'm going to guess there's nothing wrong with the YAML package then.

**Comment by vincerubinetti** [comment]
Okay so to summarize, here's what you'll have to do to fix this (unless you want to close the PR and make a new one).

[Run `build.sh` locally](https://github.com/greenelab/lab-website-template/wiki/Basic-Editing#on-your-computer) and commit all the results. The Netlify preview should succeed and show the changes. The GitHub actions will still fail, but you can still merge and it should be fine.

**Comment by arielah** [comment]
> > The GitHub actions bot is getting permission denied. I wonder if @arielah made the change if it'd successfully commit the new output file.
> 
> @arielah did you [enable github actions on your fork BEFORE making the PR](https://github.com/greenelab/lab-website-template/wiki/Basic-Editing#on-github)? That is required for the bot to work correctly. (I'm working on improving the instructions).

I did not make any changes before making the PR. 😞 I'm wondering if it would be better to just nuke the fork, nuke this PR, and start again paying more careful attention to the instructions. Thoughts?

**Comment by vincerubinetti** [comment]
@arielah That would be good. I'd like to see if doing it from a fork works since we haven't tested it that way too much. We normally do PR's from branches of this repo.

**Comment by cgreene** [comment]
I think if you copy the change you made here and do your PR as a branch instead of a fork, things will work well! 🤞

**Pull request closed without merging**
