### PR TITLE
Add pharmaceuticals preprint

### PR DESCRIPTION
**Pull request by rando2**
Add COVID-19 pharmaceuticals preprint to list of papers

### CODE REVIEW

**Comment by rando2** [comment]
This looks how I'd expect, but the job failed: https://github.com/greenelab/greenelab.com/actions/runs/625640277
@vincerubinetti just letting you know!
`error: Your local changes to the following files would be overwritten by checkout:
	_data/research-output.yml
Please commit your changes or stash them before you switch branches.`

**Comment by vincerubinetti** [comment]
It looks like you built the citations locally, and then the automatic github actions also tried to build the citations. 

I guess we don't really handle this case gracefully. We should try to avoid running the github actions when someone builds it locally.

But everything should be fine if you just go ahead with the merge.

**Review by cgreene — APPROVED** [review]
🚀

**Comment by rando2** [comment]
Thanks @vincerubinetti! My guess is maybe that happened because I did it on a branch here rather than forking? I'm not sure, but I'm glad it's not causing issues!

**Pull request merged**
