### PR TITLE
Add reproducibility standards paper to sources

### PR DESCRIPTION
**Pull request by ben-heil**

### CODE REVIEW

**Comment by cgreene** [comment]
Hmm - it looks like it built successfully but I'm not seeing it in netlify. I usually just drop an image into this issue and use the URL: https://github.com/greenelab/greenelab.com/issues/12

I wonder if it's the image or something else?

**Comment by ben-heil** [comment]
> Hmm - it looks like it built successfully but I'm not seeing it in netlify. I usually just drop an image into this issue and use the URL: #12
> 
> I wonder if it's the image or something else?

Yeah, my guess is that it is the image

**Comment by ben-heil** [comment]
It's fixed now, so I guess the image was the issue. It's weird that you can't link from the images directory :shrug:

**Comment by cgreene** [comment]
Success!

**Pull request merged**
