### PR TITLE
update research page search method

### LINKED ISSUE #61: Publications listed don't match author name
I'm not sure if this is something I can change, but I noticed that there are extra publications linked to my webpage that I think are because my name "Alex Lee" is so common. There should only be 4 publications:

* SARS-CoV-2 and COVID-19: An Evolving Review of Diagnostics and Therapeutics
* Correcting for experiment-specific variability in expression compendia can remove underlying signals
* Pseudomonas aeruginosa lasR mutant fitness in microoxia is supported by an Anr-regulated oxygen-binding hemerythrin
* The CAFA challenge reports improved protein function prediction and new functional annotations for hundreds of genes through experimental screens

### PR DESCRIPTION
**Pull request by vincerubinetti**
- implement extra `search` field on member bios to specify what strings should be searched
- implement "phrase searching" with quotes to search for complete phrases, eg. `"Alexandra Lee" genomics data`
- fix home page features
- fix start script

closes #61

### CODE REVIEW

**Comment by cgreene** [comment]
I think search without quotes might be broken now. I can't get it to work in the netlify preview. Search with quotes works great!

**Comment by ajlee21** [comment]
Looks like papers for my name are fixed. Though poking around I found that some people's papers are not found because their initial is missing:

Ariel should be "Ariel A. Hippen Anderson"
David should be "David N. Nicholson"
Halie should be "Halie M. Rando"
Casey seems to have some under "Casey Greene" and others "Casey S. Greene"

Those are the ones I found so far for current members.

**Comment by vincerubinetti** [comment]
Thanks @ajlee21, I was going to ask each lab member to add their own aliases to make sure all of their papers show up. Since you already found those, do you want to put out a slack message asking people to check, so we can add everything to this PR?

**Comment by cgreene** [comment]
@vincerubinetti can you give an example of how to do the yaml with 2 quoted versions treated as an or? I'd love to give it a shot. Is it just 2 yaml list elements?

**Comment by vincerubinetti** [comment]
image

image

**Comment by rando2** [comment]
I always use "Halie M. Rando" --  the only other possibilities I can think of are "Halie Rando" or "HM Rando". 
(Opposite of Alex, for me false negatives are way more likely than false positives)

**Comment by danich1** [comment]
I just use "David N. Nicholson". There shouldn't be any variations for me. If the middle N is removed I think my false positive rate will be quite high.

**Comment by miltondp** [comment]
Just "Milton Pividori" should work for me.

**Comment by vincerubinetti** [comment]
@arielah and @danich1 can you just commit yours since others have done that.

**Comment by vincerubinetti** [comment]
@miltondp and others, if you specify no aliases, it just uses the `title` field (what your bio page shows as your name). So if that's the same as your paper aliases, you don't need to specify any aliases.

**Comment by vincerubinetti** [comment]
@cgreene you're missing `C.S. Greene` and `C. S. Greene`

**Review by cgreene — APPROVED** [review]

**Pull request merged**
