### PR TITLE
Add long-covid preprint

### PR DESCRIPTION
**Pull request by rando2**
Updates to research.yaml to add long-covid paper
I used the final (nice) version of the wacky figure so we'll see how that works!

### CODE REVIEW

**Comment by cgreene** [comment]
We're going to have to get 👀 from @vincerubinetti. Something broke with the way the output is getting generated because the tags/thumbnails are moved but the new manuscript didn't get added.

**Comment by rando2** [comment]
The randomized thumbnails are pretty funny but I definitely agree something looks not quite right...

**Comment by vincerubinetti** [comment]
Sorry, just saw this now (my gh extension didn't notify me). This is very very weird. Your input seems correctly formatted, and no different from previous PRs. And the automatic citation script [didn't even really change](https://github.com/greenelab/greenelab.com/commit/9a87c6b5c92c2d1aae5e1b2556a2cb586cc80320#diff-86f9a26cb571a540fd7bfc0b8002559f7b61ed8781bc1cb1af26ff6cac0fe4fd), and that script is clearly what has malfunctioned. The output diff should only be like 20 lines changed (the citation of the new paper)

Will try to fix this ASAP.

**Comment by vincerubinetti** [comment]
I think I know the issue, but I am at a loss for why this particular PR caused an issue. Should have a fix in a few hours.

**Comment by vincerubinetti** [comment]
Okay I know the error. Manubot failed to cite this new paper. Could you look into why? Perhaps it is not available yet on whatever sources Manubot pulls from.

When a paper fails to be cited, currently it's treated as a soft error and leaves a blank entry, causing the offset in the metadata that you're seeing in the thumbnails. I think I should change this to a hard error that makes the whole action fail. And also I will fix the oversight where it assumes the output paper count to be the same length as the input paper count.

**Comment by rando2** [comment]
It just came out today so I might let things index and check on Monday whether there's still an issue! I'm not sure if the @https://doi.org/xxx-xx workaround would help here, but I'm also not sure how to implement it given the syntax of this file.

**Comment by vincerubinetti** [comment]
Sounds good! I am also taking this time to improve the citation script significantly besides this bug, and it'll probably take until Monday to be reviewed and merged anyway.

**Comment by vincerubinetti** [comment]
@rando2 I just updated the website from the template. You can either close this PR and open a new one from main, or merge changes from main into this one.

**Pull request closed without merging**
