### PR TITLE
remove-filter for sources.yaml

### PR DESCRIPTION
**Pull request by cgreene**
Testing what this looks like

### CODE REVIEW

**Comment by cgreene** [comment]
@vincerubinetti this picks up a few things I missed. Is it possible to filter by journal (e.g., the figshare and zenodo records) akin to the way we were filtering by file before?

Also, there are a few broken images for the Figshare datasets - not sure what's happening there but it's rendering HTML on it.

**Comment by vincerubinetti** [comment]
You can filter by anything you want using regex, but you might want to wait until I've made this upstream change for it to be a little easier:

https://github.com/greenelab/lab-website-template/issues/272

Also I noticed that HTML bug and have made an upstream fix, also coming in v1.3.0. It's because the title has a double quote in it, which prematurely closes an html attribute, which messes everything else up. As a stop gap you can add `| xml_escape`  in the citation component wherever `title` is being used:

https://github.com/greenelab/lab-website-template/commit/b33e0e4989a40456edff380dc54312b1bb078196

**Comment by cgreene** [comment]
Ok - I don't mind merging what's here and then adding the filter when 272 lands - this is quite a bit more complete & demonstrates that I definitely missed some key papers. :)

**Comment by cgreene** [comment]
Also the `xml_escape` filter will be nice when it lands - at this point unless someone compromises ORCID to inject javascript, we should be good - it's far enough down the page I doubt anyone will encounter it.

**Pull request merged**
