### PR TITLE
Update nutraceuticals preprint to published version

### PR DESCRIPTION
**Pull request by rando2**
Now published at https://doi.org/10.1128/mSystems.00122-21

### CODE REVIEW

**Comment by rando2** [comment]
@vincerubinetti I haven't had enough coffee yet so definitely possible I'm missing something, but I think there might be an error associated with the in-browser editing approach? The error message here is `error: pathspec 'patch-1' did not match any file(s) known to git` which I believe means it's failing to check out the branch these edits are on. I didn't deliberately switch to my fork or anything, just clicked the edit button on the markdown file. Figured I would ask in case you have any ideas!

**Comment by vincerubinetti** [comment]
So you did this in the GitHub UI right:

image

I just made another PR with your same changes, and it created it on a branch rather than a fork for me. The only reason I can think of is because you didn't have permissions to create a branch? Like no write permissions...

I just checked the settings for this repo, and it doesn't look like any permissions were assigned... which is strange because people have definitely made changes before. Regardless, I just gave the entire greenelab write access to this repo, so maybe if you try again next time it will work.

Also, forks should still work with the auto-cite gh-actions, but the problem is you need to make the fork first, then enable gh-actions on it, then make the pull request. Have to do it in that order for it to work. And you can't do it in that order from the github web UI.

**Comment by vincerubinetti** [comment]
#24

**Comment by rando2** [comment]
Interesting! I believe that's what I did. Next time I can try doing it the non-lazy way and see if it works better!

**Pull request closed without merging**
