### PR TITLE
Update template version, add Casey orcid, misc tweaks

### PR DESCRIPTION
**Pull request by vincerubinetti**
Reviewing the diff is impractical and not necessary, as 95% of the changes here are from the upstream template, whose changes are already reviewed in that repo. However, manually merging in the changes is an error prone process, so please instead take a look at each page of the site in the deploy preview below to make sure everything looks right. Also take a look at Casey's bio page.

- pull in updates from upstream lab-website-template
- particularly, pull in changes from this upstream pr https://github.com/greenelab/lab-website-template/pull/128 which adds ability to periodically or on-demand-ly run the auto-cite process. im using this repo/pr as a test run before merging that one.
- clear citations cache and rebuild citations from scratch
- opt-in to orcid plugin and add Casey's orcid
- list all of Casey's orcid papers on his bio page
- update AHSB 
- Alex and David to alumni :(

### CODE REVIEW

**Review by cgreene — APPROVED** [review]
page looks as expcted! 🙌

**Comment by vincerubinetti** [comment]
Thanks for the quick review @cgreene , let's get a second pair of eyes on the pages before merge to make sure there's no "lorem ipsums" that got left in and etc.

**Comment by arielah** [comment]
Looks good to me! Didn't see any broken links or lorem ipsums. This is a content change, not a formatting change, but Alex and David should maybe be moved to alumni on the team page 😢

**Review by arielah — APPROVED** [review]

**Comment by cgreene** [comment]
@arielah 
> This is a content change, not a formatting change, but Alex and David should maybe be moved to alumni on the team page 😢

😭 😭

**Pull request merged**
