### PR TITLE
add new microbe review paper

### PR DESCRIPTION
**Pull request by ajlee21**

### CODE REVIEW

**Comment by ajlee21** [comment]
All checks passed but looks like the `citations.yml` wasn't generated. Not sure if I messed something up with all the tries.

**Comment by cgreene** [comment]
I just re-triggered the auto cite run @vincerubinetti - maybe github actions was having issues?

**Comment by vincerubinetti** [comment]
Apologies. Last week when I was troubleshooting, I changed some things in the main branch of the repo, and that broke this.

From what I can understand from testing, the trigger `pull_request` is needed when working from branches, and `pull_request_target` is needed when working from forks (but still seems to be insufficient in my most recent tests). I remember having just both triggers in there in the past, but it confused people because one would always fail, depending on which method you used.

I still don't have a clean solution for this, other than forcing people to use branches.

The problem above was basically that the `arxiv` paper you added wasn't even showing up in the checked out code, perhaps because in this case `pull_request_target` (usually supposed to refer to a fork?) is referring to `main`...

**Comment by cgreene** [comment]
Woo! 🎊  There it is! https://github.com/greenelab/greenelab.com/pull/51/commits/f3776a32f8666e3e15f5d41a5703a856ad401a4d

@ajlee21 does this look ok to you?

**Review by cgreene — APPROVED** [review]
Approved from my point of view - @ajlee21 please check that this is what you wanted. I think your prior PR might have had more changes?

**Comment by ajlee21** [comment]
Thank you @vincerubinetti ! The added publication looks great! 

I did have some additional changes that I can put into a separate PR to make things cleaner. For those changes, I wanted to update some of the existing citations (i.e. add links and change an image). In that case, I would still change the sources.yml file, correct? There's a paper that is now published that the website is still pointing to the preprint that I wasn't sure if that was something I could update.

**Comment by cgreene** [comment]
@ajlee21 : yup - edit the sources.yml. I saw that in one case you wanted to update authors - you can copy the authors from citations.yml and then fix them in sources.yml and my understanding is that it will override the auto-cited fields.

**Comment by vincerubinetti** [comment]
Yep that's right, it should work. Also it seems like `pull_request_target` was changed to `pull_request` in `main`, so you shouldn't have an issue on your next PR (as long as your local copy is up to date).

**Pull request merged**
