### PR TITLE
Update PR template to mention .yml

### PR DESCRIPTION
**Pull request by rando2**
It always bothers me that the file extension I modify most often is not in the directions 😆 
Sorry for my neuroses, @vincerubinetti!

### CODE REVIEW

**Comment by vincerubinetti** [comment]
I think we can simplify this a bit actually.

```
Request a review from @cgreene if you're changing Markdown files (.md), image files (.jpg, .png, etc.) (except for /favicons), or YAML files (.yml) in /_data. 

Request a review from @vincerubinetti (or someone else very knowledgeable in the template and its technologies) if you're changing anything else.

When in doubt, request a review from both.
```

**Review by vincerubinetti — CHANGES_REQUESTED** [review]
```
Request a review from @cgreene if you're changing Markdown files (.md), image files (.jpg, .png, etc.) (except for /favicons), or YAML files (.yml) in /_data. 

Request a review from @vincerubinetti (or equivalent expertise in the template) if you're changing anything else.

When in doubt, request a review from both.
```

**Comment by rando2** [comment]
That sounds good to me @vincerubinetti -- I copy & pasted in your text

**Comment by vincerubinetti** [comment]
Looks good! Thanks for incorporating. Merge when ready.

**Review by vincerubinetti — APPROVED** [review]

**Pull request merged**
